### ISSUE TITLE
Why are mounting_dowel and mounting_dowel_sleeve two separate files ?

### ISSUE THREAD

**Issue by azsde** [mwood77/osww#9]
Hi

I am wondering why those are two separate files that needs to be pressed together ?

Isn't it simpler to just "merge them" and have a cylinder with a bigger diameter on one part and a smaller diameter on the rest of the part ?

**Comment by mwood77** [comment]
Hi,

These pieces were created separately as press-fit, because I cannot guarantee the tolerances of all printers. These pieces interact not only with themselves, but also a metal rod, and a bearing's inner-race. So there's the potential of a lot going wrong.

If they were merged into a single print, the chances of failure are much higher. For example, if the bottom of the larger print delaminates from the print bed, the mounting hole could become warped and the print has to be re-done. That's a bummer as it's a 3+ hour print.

Separating the pieces into a larger print + a smaller high-tolerance print means that, should the tolerance(s) need to be adjusted for your situation, it's a re-size of a basic cylinder and a printing time of 5 minutes.
